Intentional failed smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -393,9 +393,9 @@ jobs:
             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
             then
-                exit 0
-            else
                 exit 1
+            else
+                exit 2
             fi
 
       - destroy-environment
@@ -498,9 +498,9 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
-      - notify_on_success:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend, deploy-infrastructure, configure-infrastructure, run-migrations, deploy-frontend, deploy-backend, smoke-test, cloudfront-update, cleanup]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
+      # - notify_on_success:
+      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend, deploy-infrastructure, configure-infrastructure, run-migrations, deploy-frontend, deploy-backend, smoke-test, cloudfront-update, cleanup]
